name: Build Release

on:
  workflow_call:
    inputs:
      repos:
        type: string
        description: "https://vpm.nadena.dev/vpm.json\nhttps://example.com/index.json"
      ma:
        type: boolean
        description: "add https://vpm.nadena.dev/vpm.json to repos"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: get packageName
        id: packageName
        uses: notiz-dev/github-action-json-property@7a701887f4b568b23eb7b78bb0fc49aaeb1b68d3
        with:
          path: "package.json"
          prop_path: "name"

      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@7a701887f4b568b23eb7b78bb0fc49aaeb1b68d3
        with:
          path: "package.json"
          prop_path: "version"

      - name: Set Environment Variables
        run: |
          echo "zipFile=${{ steps.packageName.outputs.prop }}-${{ steps.version.outputs.prop }}".zip >> $GITHUB_ENV
          echo "unityPackage=${{ steps.packageName.outputs.prop }}-${{ steps.version.outputs.prop }}-novcc.unitypackage" >> $GITHUB_ENV
          echo "unityPackageZipFile=${{ steps.packageName.outputs.prop }}-${{ steps.version.outputs.prop }}-novcc.zip" >> $GITHUB_ENV
          echo "vpaiLatestFile=${{ steps.packageName.outputs.prop }}-instaler.unitypackage" >> $GITHUB_ENV
          echo "vpaiLatestZipFile=${{ steps.packageName.outputs.prop }}-instaler.zip" >> $GITHUB_ENV
          echo "vpaiVersionFile=${{ steps.packageName.outputs.prop }}-${{ steps.version.outputs.prop }}-instaler.unitypackage" >> $GITHUB_ENV
          echo "vpaiVersionZipFile=${{ steps.packageName.outputs.prop }}-${{ steps.version.outputs.prop }}-instaler.zip" >> $GITHUB_ENV
          if [ ${{ inputs.ma }} = true ]; then
            echo "marepos=https://vpm.nadena.dev/vpm.json" >> $GITHUB_ENV
          fi

      - name: remove doc~
        run: rm -rf doc~

      - name: Create Zip
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "."
          filename: "${{env.zipFile}}" # make the zip file two directories up, since we start two directories in above
          exclusions: "*.git*"

      - name: mkdir Packages
        run: mkdir Packages

      - name: Checkout for unitypackage
        uses: actions/checkout@v3 # check out automation repo
        with:
          path: Packages/${{steps.packageName.outputs.prop}}
          clean: false # otherwise the local repo will no longer be checked out

      - run: find "Packages/${{steps.packageName.outputs.prop}}" -name \*.meta >> metaList

      - name: Create UnityPackage
        uses: pCYSl5EDgo/create-unitypackage@cfcd3cf0391a5ef1306342794866a9897c32af0b
        with:
          package-path: ${{ env.unityPackage }}
          include-files: metaList

      - name: Create UnityPackage Zip
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "."
          path: ${{ env.unityPackage }}
          filename: "${{env.unityPackageZipFile}}"

      - name: Create VPAI latest
        uses: anatawa12/sh-actions/create-vpai@ab722329dbdc558dd9cc8e7bc89bb61d2df21ba0
        with:
          repositories: |
            https://vpm.narazaka.net/index.json
            ${{ inputs.repos }}
            ${{ env.marepos }}
          packages: ${{ steps.packageName.outputs.prop }}@^${{ steps.version.outputs.prop }}
          output: "${{ env.vpaiLatestFile }}"
      - name: Create VPAI latest Zip
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "."
          path: ${{ env.vpaiLatestFile }}
          filename: ${{ env.vpaiLatestZipFile }}
      - name: Create VPAI version
        uses: anatawa12/sh-actions/create-vpai@ab722329dbdc558dd9cc8e7bc89bb61d2df21ba0
        with:
          repositories: |
            https://vpm.narazaka.net/index.json
            ${{ inputs.repos }}
          packages: ${{ steps.packageName.outputs.prop }}@${{ steps.version.outputs.prop }}
          output: "${{ env.vpaiVersionFile }}"
      - name: Create VPAI version Zip
        uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
        with:
          type: "zip"
          directory: "."
          path: ${{ env.vpaiVersionFile }}
          filename: ${{ env.vpaiVersionZipFile }}

      - name: Make Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        with:
          tag_name: v${{ steps.version.outputs.prop }}
          files: |
            ${{ env.zipFile }}
            ${{ env.vpaiLatestZipFile }}
            ${{ env.vpaiVersionZipFile }}
            ${{ env.unityPackageZipFile }}
            package.json
